### ISSUE TITLE
Yeni README'ye ihtiyacınız var.

### ISSUE THREAD

**Issue by Akileus77** [kodbilenadam/KodBilenBotTwitch#2]
Lütfen README.md 'yi güncelleyin.

**Comment by kodbilenadam** [comment]
Şu anda README.md yi güncelleyebilecek durumda değilim. Eğer müsait olursanız lütfen siz güncelleyin.

**Comment by Akileus77** [comment]
Tamamdır, en kısa sürede PR atacağım.

**Comment by kodbilenadam** [comment]
PR onaylandı.
